http:
  protocol: "HTTP"
  host: "0.0.0.0"
  port: "8081"
  path: "/action"
mule:
  version: "4.4.0"  
  
cloudhub:
  username: "SelfLearn"
  password: "LearnMule#2023"
  bg: "Student"
  appName: "githubandmule"
  environment: "Sandbox"
  region: "us-east-2"
  workerType: "Micro"
  workers: "1"


